spring:
  application:
    name: Library
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/data/DBlibrary
    username: lucas
    password: 123
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
