spring:
  application:
    name: Library
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library_db
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
efi:
  pix:
    client-id: ${client_id}
    client-secret: ${client_secret}
    certificate-path: ./certs/producao-853053-library.p12
    sandbox-enabled: false
