spring:
  application:
    name: Library
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/DBlibrary
    username: lucas
    password: 123
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
efi:
  pix:
    client-id: ${client_id}
    client-secret: ${client_secret}
    certificate-path: ./certs/producao-853053-library.p12
    sandbox-enabled: false
